### ISSUE TITLE
Zooz ZEN17

### ISSUE THREAD

**Issue by AlistairWallace** [koktail-nl/com.getzooz.issues#2]
Describe the bug
ZEN17 Not showing Child Devices with Homey Pro 2023

To Reproduce

- Add ZEN17 to HomeyPro 2023
- Three Devices Appear (Relay1, Relay 2 and Relay Control)
- Missing are the Two Dry Contact Sensor Inputs

Additional context
According to the instructions, if you wish to have the inbound Child Dry contacts, you have to set the parameters to enable the feature, and then remove and re-add the ZEN17.

On doing so, the steps seem to reset the device during the process and the Child devices never appear.

**Comment by bushtor** [comment]
Hi,
I purchased two ZEN17 ver. 1.0 Universal relay with firmware ver 1.04 and they both 5 digit DSK IDs.

When adding the device to Homey Pro 2019 it accepts immediately the two first steps but after having entered the correct 5 digit DSK ID it waits for 5 seconds and then it displays: "Something went wrong while communicating with the device".

Both my ZEN17 boxes behaves in the exact same manner, so it cannot be a HW failure.

What can I do in order to get my devices registered?  It is really important for me.
Have you tested the app with the ZEN17 ?
Best regards from Norway

**Comment by koktaildotcom** [comment]
I didn't implement and test the behaviour of the dry contacts unfortunately. 

I will have a look if that's possible.

**Comment by bushtor** [comment]
Thanks a lot.  That feature is very important for me too....

Do you also have some thoughts why I couldn't pair my ZEN17 devices with their own DSK ID but had to use 00000 instead..?
